CREATE PROC FI_SP_ConsBenef
	@IDCLIENTE BIGINT
AS
BEGIN
	IF(ISNULL(@IDCLIENTE,0) = 0)
		SELECT CPF, NOME, IDCLIENTE, ID FROM BENEFICIARIOS WITH(NOLOCK) 
	ELSE
		SELECT CPF, NOME, IDCLIENTE, ID FROM BENEFICIARIOS WITH(NOLOCK) WHERE IDCLIENTE = @IDCLIENTE
END